#!/bin/bash

echo "=== NGINX Troubleshooting Guide ==="
echo ""
echo "Run these commands on your server to diagnose the issue:"
echo ""
echo "1. Check nginx configuration syntax:"
echo "   sudo nginx -t"
echo ""
echo "2. View nginx error logs:"
echo "   sudo tail -50 /var/log/nginx/error.log"
echo ""
echo "3. Check if nginx is running:"
echo "   sudo systemctl status nginx"
echo ""
echo "4. View the current nginx config:"
echo "   sudo cat /etc/nginx/sites-available/api.hyrmate.com"
echo ""
echo "5. Restart nginx (if config is valid):"
echo "   sudo systemctl restart nginx"
echo ""
echo "6. Test CORS headers:"
echo "   curl -I -X OPTIONS https://api.hyrmate.com/api/v1/jobs/batches \\"
echo "     -H 'Origin: https://app.hyrmate.com' \\"
echo "     -H 'Access-Control-Request-Method: GET' \\"
echo "     -H 'Access-Control-Request-Headers: Content-Type'"
echo ""
