"""Add user profile fields

Revision ID: cc7250d554a1
Revises: a1b2c3d4e5f6
Create Date: 2025-11-29 19:53:16.888187

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cc7250d554a1"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_credit_transactions_id", table_name="credit_transactions")
    op.drop_index("ix_credit_transactions_user_id", table_name="credit_transactions")
    op.drop_table("credit_transactions")
    op.drop_index("ix_activities_id", table_name="activities")
    op.drop_index("ix_activities_user_id", table_name="activities")
    op.drop_table("activities")
    op.add_column("users", sa.Column("first_name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("last_name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("phone_number", sa.String(), nullable=True))
    op.add_column("users", sa.Column("location", sa.String(), nullable=True))
    op.add_column("users", sa.Column("bio", sa.String(), nullable=True))
    op.add_column("users", sa.Column("job_title", sa.String(), nullable=True))
    op.add_column("users", sa.Column("department", sa.String(), nullable=True))
    op.add_column("users", sa.Column("profile_image_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "profile_image_url")
    op.drop_column("users", "department")
    op.drop_column("users", "job_title")
    op.drop_column("users", "bio")
    op.drop_column("users", "location")
    op.drop_column("users", "phone_number")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.create_table(
        "activities",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("job_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("cv_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "activity_type",
            postgresql.ENUM(
                "JOB_CREATED",
                "CV_UPLOADED",
                "CV_PROCESSED",
                "CV_FAILED",
                "JOB_CLOSED",
                "JOB_REOPENED",
                name="activitytype",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("metadata_json", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["cv_id"], ["cvs.id"], name="activities_cv_id_fkey"),
        sa.ForeignKeyConstraint(
            ["job_id"], ["cv_batches.id"], name="activities_job_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="activities_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="activities_pkey"),
    )
    op.create_index("ix_activities_user_id", "activities", ["user_id"], unique=False)
    op.create_index("ix_activities_id", "activities", ["id"], unique=False)
    op.create_table(
        "credit_transactions",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM("PURCHASE", "USAGE", name="credit_txn_type_final"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("amount", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("balance_after", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="credit_transactions_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="credit_transactions_pkey"),
    )
    op.create_index(
        "ix_credit_transactions_user_id",
        "credit_transactions",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_credit_transactions_id", "credit_transactions", ["id"], unique=False
    )
    # ### end Alembic commands ###
