"""add credits

Revision ID: a1b2c3d4e5f6
Revises: 4d4d65af3cac
Create Date: 2025-11-30 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a1b2c3d4e5f6"
down_revision = "4d4d65af3cac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_transactions",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "type",
            sa.Enum("PURCHASE", "USAGE", name="credit_txn_type_final"),
            nullable=False,
        ),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("balance_after", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_credit_transactions_id"), "credit_transactions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_credit_transactions_user_id"),
        "credit_transactions",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "users",
        sa.Column("credits", sa.Integer(), nullable=False, server_default="100"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "credits")
    op.drop_index(
        op.f("ix_credit_transactions_user_id"), table_name="credit_transactions"
    )
    op.drop_index(op.f("ix_credit_transactions_id"), table_name="credit_transactions")
    op.drop_table("credit_transactions")
    sa.Enum(name="credit_txn_type_final").drop(op.get_bind())
    # ### end Alembic commands ###
