"""add job fields

Revision ID: 4d4d65af3cac
Revises:
Create Date: 2025-11-28 15:18:46.484729

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4d4d65af3cac"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cv_batches", sa.Column("title", sa.String(), nullable=False))
    op.add_column("cv_batches", sa.Column("department", sa.String(), nullable=True))
    op.add_column("cv_batches", sa.Column("location", sa.String(), nullable=True))
    op.add_column("cv_batches", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "cv_batches", sa.Column("job_description_text", sa.Text(), nullable=True)
    )
    op.add_column("cv_batches", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.drop_column("cv_batches", "batch_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cv_batches",
        sa.Column("batch_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("cv_batches", "is_active")
    op.drop_column("cv_batches", "job_description_text")
    op.drop_column("cv_batches", "description")
    op.drop_column("cv_batches", "location")
    op.drop_column("cv_batches", "department")
    op.drop_column("cv_batches", "title")
    # ### end Alembic commands ###
